### ISSUE TITLE
Home users should not be allowed to signout

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#50]
When a member of Home (either managed user or account holder) is using the WebApp, there is an option to sign out.  This prevents any other home user from being able to use the WebApp until the Admin is able to log back in.

I taught my kids to log out when ever using the Web so this is messing things up.  :-)

Ideally, the sign out option should only be for the admin.  Users should just see switch user.

**Comment by ericmatthys** [comment]
Thanks for the report. We're tracking this issue internally now. Closing this one out.
