### ISSUE TITLE
PlexHome members cannot edit playlist title

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#51]
2.3.20

Admin account has no problem.  Other users, both plex.tv accounts and managed users, when editing a playlist, get a message that the changes could not be saved.  Also cannot add anything into the comment box either.  Creating the playlist, moving items around, deleting items, all work fine.  Only editing the title or comment fails.

**Comment by ericmatthys** [comment]
Known server issue that should be fixed in the next PMS update I believe. Thanks for the report though!
