### ISSUE TITLE
FireFox now supports H264 High Profile - Need to add experimental player

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#52]
On the latest version of FireFox I have for Windows 36.0.4, I can play high profile videos just fine using their built-in html5 player.  So I think the option to use the experimental player should now be included.

**Comment by ericmatthys** [comment]
The experimental player setting is automatically exposed based on if we detect support for it. You'd need to enable media source extensions in Firefox to see it, since this only applies to transcoded video. Direct play mp4s will use the html player regardless.
