### ISSUE TITLE
When viewing TV Shows, filter are not correct when switching from Show/Season/Episode

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#54]
If you start at Show Type and set the Unwatched filter, it is fine.  But then changing to Season or Episode Type, the listing is all wrong.  If you start at the Episode Type and set filter to Unwatched, it is fine.  Switching to Season or Show is again messed up.  If you start at the Season Type, you cannot set the Unwatched filter.

Start with Show
![show](https://cloud.githubusercontent.com/assets/10193847/7335729/ec6d3f96-eb85-11e4-9c0c-157352610789.png)

Star with Episode
![episode](https://cloud.githubusercontent.com/assets/10193847/7335731/ef8ac310-eb85-11e4-818c-4a4f816d06da.png)

**Comment by PlexMovieFan** [comment]
Oops.  Second image of second image show say "ALL SEASONS LISTED ??"

**Comment by ericmatthys** [comment]
Thanks for the report. This should be fixed in the next release.

**Comment by PlexMovieFan** [comment]
LOL, the fix was to remove the filter when switching types.  I was hoping for a better behavior of keeping the filter if applicable, but this will do.

**Comment by ericmatthys** [comment]
Filters don't really carry over between types, so you'd end up with a season unwatched filter when seasons don't actually have an unwatched filter. We'd have to take on more responsibility of the filter listing from the server since the server provides all those filters.

**Comment by PlexMovieFan** [comment]
Just curious why there is no unwatched by season.  If I go into the series view, it lists the seasons and there are unwatched markers per season, so it appears that the server already knows the watched status by season.  It's fine if it is not possible, just thought it was strange since the information appears to be there.

**Comment by ericmatthys** [comment]
It's possible, but the server just doesn't return it as a filter for clients to display. Clients would have to build the query themselves. I can't speak for why the server doesn't return it, but I think in general, seasons aren't really expected to be navigated at the library level.
