### ISSUE TITLE
Editing background and banner to a season does not work as expected.

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#56]
When adding a background, the window says it was uploaded and the background does show up, but nothing gets populated into the window so you can choose between different backgrounds.

Checking the database, the entry is correctly added to user_arl_url.

The support article on local tv show data does not mention season backgrounds.  Looking in the local media scanner code, there is nothing for season background either.  So should this not be possible?

The article also describes season banners but there is no spot to add then from the edit screen.  Scanner code looks for banners too.

**Comment by ericmatthys** [comment]
I filed a server issue for the background not being listed for a season. I think we've historically only shown banners for shows, but I'll ask about that.
